FROM python:3.10-slim

RUN apt update
RUN apt install -y --no-install-recommends texlive-latex-base

WORKDIR /app
COPY . /app

RUN pip install latex-generator-no-mercy==0.1.0
RUN python3 main.py
RUN pdflatex document_with_table_and_image.tex
CMD ["pdflatex", "document_with_table_and_image.tex"]
